### ISSUE TITLE
[BUG] Slot regression between v2.1.5 and v.2.2.1

### ISSUE THREAD

**Issue by ouamer-dahmani** [rodrigopivi/Chatito#69]
Hi,

I just updated to 2.2.1 and noticed a big regression: the slots are not correctly substituted.

You will find attached a simple repro chatito file with the generated rasa datasets.
[repro.zip](https://github.com/rodrigopivi/Chatito/files/3227620/repro.zip)

**Comment by ouamer-dahmani** [comment]
If I remove the synonym substitution and simply use the value in the rasa adapter it starts working correctly again.
```
acc.entities.push({
                        end: acc.text.length + next.value.length,
                        entity: next.slot,
                        start: acc.text.length,
                        value: next.value
                    });
```

**Comment by rodrigopivi** [comment]
Hi @ouamer-dahmani ,

There was indeed a bug with the rasa adapter where the actual synonyms were not being generated correctly, this is now fixed in v2.2.2 , but i'm not sure it is the same problem you are reporting.

One particular behavior of the rasa adapter is that when you have a single alias defined inside an slot, the slot values will be mapped as synonyms, so for your particular example:

```
%[test_intent]('training': '6')
    @[wit$number:role]

@[wit$number:role]
    ~[small_number]

~[small_number]
    one
    two
    three
    1
    2
    3
```

The generated dataset will map all values of slot `@[wit$number:role]` to `small_number` as expected, if you would like to avoid that alias mapping for rasa, then this would work:

```
%[test_intent]('training': '6')
    @[wit$number:role]

@[wit$number:role]
    ~[1]
    ~[2]
    ~[3]

~[1]
    one
    1

~[2]
   two
    2

~[3]
    three
    3
```

This way you would get better synonyms, as one would be replaced with `1`. Let me know if that works for your use case.

**Comment by ouamer-dahmani** [comment]
Hi, thanks for the answer.

If small_number goes all the way to 100, rewriting this becomes quite painful.

Would something like this work or will it still see a single alias?
```
@[wit$number:role]
    ~[small_number]
    ~[small_number]
```

Otherwise maybe we could consider a generation option that allows control over synonym behavior?

**Comment by rodrigopivi** [comment]
Yes, that may be a good addition to be considered in future releases.

**Comment by rodrigopivi** [comment]
Done at 2.3.0. Now the alias behavior also requires an argument.
